'use client';

import React from 'react';
import Link from 'next/link';
import { Play, ArrowRight, Clock, Video, CheckSquare, Target, Cpu } from 'lucide-react';

interface DailyLearningCommandCenterProps {
  planData?: {
    items: Array<{
      step_number: string;
      action_type: 'WATCH' | 'PRACTICE' | 'ASSESS' | 'APPLY';
      title: string;
      duration_minutes: number;
      subject_name: string;
      target_url: string;
    }>;
    total_duration_formatted: string;
    learning_twin_rationale: string;
  };
}

export const DailyLearningCommandCenter: React.FC<DailyLearningCommandCenterProps> = ({
  planData,
}) => {
  const p = planData || {
    items: [
      {
        step_number: '01',
        action_type: 'WATCH' as const,
        title: 'SQL Window Functions & Frame Specifications',
        duration_minutes: 32,
        subject_name: 'SQL Analytics',
        target_url: '/courses/databases',
      },
      {
        step_number: '02',
        action_type: 'PRACTICE' as const,
        title: '5 Window Function Partition & Ranking Problems',
        duration_minutes: 25,
        subject_name: 'SQL Analytics',
        target_url: '/practice',
      },
      {
        step_number: '03',
        action_type: 'ASSESS' as const,
        title: 'Window Functions Automated Checkpoint',
        duration_minutes: 15,
        subject_name: 'SQL Analytics',
        target_url: '/assessments',
      },
      {
        step_number: '04',
        action_type: 'APPLY' as const,
        title: 'Business Revenue Cohort Analysis Challenge',
        duration_minutes: 40,
        subject_name: 'SQL Analytics',
        target_url: '/projects',
      },
    ],
    total_duration_formatted: '1h 52m',
    learning_twin_rationale:
      'Dynamically generated by your Cognitive Learning Twin to patch detected conceptual gaps in DENSE_RANK() and window framing boundaries.',
  };

  const getActionBadge = (type: string) => {
    switch (type) {
      case 'WATCH':
        return <span className="px-2 py-0.5 bg-blue-100 text-blue-900 dark:bg-blue-950 dark:text-blue-300 font-mono text-[10px] font-bold border border-blue-200 dark:border-blue-800">WATCH</span>;
      case 'PRACTICE':
        return <span className="px-2 py-0.5 bg-amber-100 text-amber-900 dark:bg-amber-950 dark:text-amber-300 font-mono text-[10px] font-bold border border-amber-200 dark:border-amber-800">PRACTICE</span>;
      case 'ASSESS':
        return <span className="px-2 py-0.5 bg-purple-100 text-purple-900 dark:bg-purple-950 dark:text-purple-300 font-mono text-[10px] font-bold border border-purple-200 dark:border-purple-800">ASSESS</span>;
      case 'APPLY':
        return <span className="px-2 py-0.5 bg-emerald-100 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-300 font-mono text-[10px] font-bold border border-emerald-200 dark:border-emerald-800">APPLY</span>;
      default:
        return null;
    }
  };

  return (
    <div className="w-full bg-[#fdfcf9] dark:bg-stone-900 border border-stone-300 dark:border-stone-800">
      {/* Header */}
      <div className="px-6 py-4 border-b border-stone-200 dark:border-stone-800 bg-[#f9f8f4] dark:bg-stone-950 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <span className="w-2.5 h-2.5 bg-amber-600 dark:bg-amber-400"></span>
          <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-stone-900 dark:text-stone-100">
            SECTION 09 // TODAY'S AI LEARNING COMMAND PLAN
          </h2>
        </div>
        <div className="flex items-center gap-3 font-mono text-xs">
          <span className="text-stone-500 uppercase">TOTAL ESTIMATED TIME:</span>
          <span className="font-bold text-stone-900 dark:text-white bg-white dark:bg-stone-800 px-2 py-0.5 border border-stone-300 dark:border-stone-700">
            {p.total_duration_formatted}
          </span>
        </div>
      </div>

      <div className="p-6 md:p-8 space-y-6">
        {/* Rationale note */}
        <div className="p-3 bg-stone-100/70 dark:bg-stone-800/50 border-l-2 border-amber-600 text-xs font-sans text-stone-700 dark:text-stone-300">
          <span className="font-mono font-bold text-[10px] uppercase text-stone-500 block mb-0.5">
            LEARNING TWIN RATIONALE:
          </span>
          {p.learning_twin_rationale}
        </div>

        {/* 4-Step Action Flow Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {p.items.map((item, idx) => (
            <div
              key={idx}
              className="p-5 bg-white dark:bg-stone-800 border border-stone-200 dark:border-stone-700 flex flex-col justify-between space-y-4 hover:border-stone-400 transition-colors"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between font-mono">
                  <span className="text-2xl font-serif font-bold text-stone-400 dark:text-stone-500">
                    {item.step_number}
                  </span>
                  {getActionBadge(item.action_type)}
                </div>

                <div>
                  <div className="text-[10px] font-mono text-stone-400 uppercase">
                    {item.subject_name}
                  </div>
                  <h4 className="text-sm font-serif font-bold text-stone-900 dark:text-white mt-1 leading-snug">
                    {item.title}
                  </h4>
                </div>
              </div>

              <div className="pt-3 border-t border-stone-100 dark:border-stone-700/80 flex items-center justify-between font-mono text-xs">
                <span className="text-stone-500">{item.duration_minutes} min</span>
                <Link
                  href={item.target_url}
                  className="text-blue-700 hover:text-blue-900 dark:text-blue-400 font-bold inline-flex items-center gap-1"
                >
                  <span>START</span>
                  <ArrowRight size={12} />
                </Link>
              </div>
            </div>
          ))}
        </div>

        {/* Global Action Button */}
        <div className="pt-2">
          <Link
            href={p.items[0]?.target_url || '/courses/databases'}
            className="w-full py-3.5 px-6 bg-stone-950 hover:bg-stone-900 text-white font-mono text-xs font-bold uppercase tracking-widest flex items-center justify-center gap-2 transition-all shadow-md"
          >
            <Play size={14} className="fill-white" />
            <span>START TODAY&apos;S COMPLETE PLAN ({p.total_duration_formatted})</span>
          </Link>
        </div>
      </div>
    </div>
  );
};
